// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI Styling Assistant.
 *
 * - getStylingAdvice - A function that generates styling advice based on user input.
 * - GetStylingAdviceInput - The input type for the getStylingAdvice function.
 * - GetStylingAdviceOutput - The return type for the getStylingAdvice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetStylingAdviceInputSchema = z.object({
  styleDescription: z.string().describe('The description of the desired style.'),
  styleImage: z
    .string()
    .optional()
    .describe(
      "A photo of a desired style, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type GetStylingAdviceInput = z.infer<typeof GetStylingAdviceInputSchema>;

const GetStylingAdviceOutputSchema = z.object({
  advice: z.string().describe('The tailored styling advice.'),
});
export type GetStylingAdviceOutput = z.infer<typeof GetStylingAdviceOutputSchema>;

export async function getStylingAdvice(input: GetStylingAdviceInput): Promise<GetStylingAdviceOutput> {
  return getStylingAdviceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getStylingAdvicePrompt',
  input: {schema: GetStylingAdviceInputSchema},
  output: {schema: GetStylingAdviceOutputSchema},
  prompt: `You are a professional styling assistant who provides useful advice based on user preference. 

  You will use this information to suggest how the user can achieve the desired style. Provide detailed steps, including products, tools, and techniques.

  User Description: {{{styleDescription}}}
  {{#if styleImage}}
  User Image: {{media url=styleImage}}
  {{/if}}`,
});

const getStylingAdviceFlow = ai.defineFlow(
  {
    name: 'getStylingAdviceFlow',
    inputSchema: GetStylingAdviceInputSchema,
    outputSchema: GetStylingAdviceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
